
# ===============================
# Server Property
# ===============================
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
  security:
    jwt:
      secret: "My secret key"
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: ${CORS_ALLOWED_METHODS}
  data:
    redis:
      host: localhost
      port: 6379
      password: "1111"


logging:
  level:
    com.aoxx.oauth: DEBUG  # 특정 패키지에만 DEBUG 주고 싶으면 이렇게
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
