server:
  port: 8081

# ===============================
# local Server Property
# ===============================
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: web_service
        format_sql: true
    open-in-view: false

# 로깅
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace