# ===============================
# Server Property
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    ddl-auto: update
    properties:
      hibernate:
        default_schema: spring
