# ===============================
# Server Property
# ===============================
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=spring"
    username: "postgres"
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: spring
  security:
    jwt:
      secret: "My secret key"
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  data:
    redis:
      host: localhost
      port: 6379
      password: "1111"


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE